import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "@/css/css-overrides.css";
import "./globals.css";
import { CartProvider } from "@/providers";
import { MainNav } from "@/components";

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <CartProvider>
        <body className={`${dmSans.className} antialiased`}>
          <MainNav />
          {children}
        </body>
      </CartProvider>
    </html>
  );
}
